// Generated by https://quicktype.io

export class PostDTO {
    id:          number = 0;
    titulo:      string = "";
    texto:       string = "";
    urlFoto1:    string = "";
    urlFoto2:    string = "";
    visibilidad: string = "";
    nickname:    string = "";
    fotoPerfil:  string = "";
    likes:       number = 0;
}
