// Generated by https://quicktype.io

export interface PostResponse {
    content:          Post[];
    pageable:         Pageable;
    totalPages:       number;
    totalElements:    number;
    last:             boolean;
    size:             number;
    number:           number;
    sort:             Sort;
    numberOfElements: number;
    first:            boolean;
    empty:            boolean;
}

export interface Post {
    id:          number;
    titulo:      string;
    texto:       string;
    urlFoto1:    string;
    urlFoto2:    string;
    visibilidad: string;
    nickname:    string;
    fotoPerfil:  string;
    likes:       number;
}

export interface Pageable {
    sort:       Sort;
    offset:     number;
    pageNumber: number;
    pageSize:   number;
    unpaged:    boolean;
    paged:      boolean;
}

export interface Sort {
    empty:    boolean;
    sorted:   boolean;
    unsorted: boolean;
}
