// Generated by https://quicktype.io

export class RegisterDTO {
    nickname:        string = "";
    avatar:          string = "";
    fullname:        string = "";
    fechaNacimiento: string = "";
    email:           string = "";
    password:        string = "";
    password2:       string = "";
    visibilidad:     string = "";
}
