// Generated by https://quicktype.io

export interface RegisterResponse {
    id:               string;
    nickname:         string;
    descripcion:      string;
    foto:             string;
    publicaciones:    any[];
    numeroSeguidores: number;
    numeroSiguiendo:  number;
    visibilidad:      string;
}
